services:
  - type: web
    name: csv-url-comparison-tool
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
    buildFilter:
      paths:
        - requirements.txt
        - runtime.txt 
